name: yunyu_study
description: 云屿小学学业辅导工具
version: 2.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  http: ^1.2.0
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
